[feat]: subscription api 구현
kakao-tech-campus-2nd-step3/Team3_BE pull request #21
Opened 2024-09-25 03:32 UTC by ez23re

## 📄요약

> subscription CRUD 및 단위테스트 작성

## 🖋️작업 내용

- [ ]  api 명세대로 controller 메소드 작성
- [ ] 구독조회, 구독취소, 구독하기 서비스 로직 작성
- [ ] 단위테스트 작성

## 📷스크린샷
![스크린샷 2024-09-25 094251](https://github.com/user-attachments/assets/a7b053d0-03ed-4458-a3c1-b33810c40dcf)

## ❗참고 사항

## 🔗이슈
close #17

2024-09-25 07:03 UTC, kanguk01 reviewed
눈에 띄는 부분을 코멘트해봤는데 한번 봐주세요!

2024-09-25 07:03 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/Subscription/service/SubscriptionService.java
> +        return ResponseEntity.ok(response);
[질문] Dto를 사용하지 않고 Map을 사용한 이유가 있으신가요??

2024-09-25 07:03 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/Subscription/service/SubscriptionService.java
> +        return ResponseEntity.ok(response);
마찬가지로 다른 부분도 해당입니다!

2024-09-25 07:28 UTC, ez23re commented on src/main/java/com/splanet/splanet/Subscription/dao/SubscriptionDao.java
service에 너무 많은 로직이 들어간 것 같아서 db접근 로직은 따로 두면 깔끔해질까 싶어서 만들어봤습니다.

2024-09-25 07:31 UTC, ez23re commented on src/main/java/com/splanet/splanet/Subscription/service/SubscriptionService.java
> +        return ResponseEntity.ok(response);
원래 dto를 사용했었는데 api 명세서대로 응답에 필요한 키값만 받고 싶어서 Map<>을 사용했습니다. 지금은 처음 단계지만 리팩토링 하다가 코드가 길어지면 정말 가독성이 떨어질 수 있을 것 같네요!

2024-09-25 17:54 UTC, kanguk01 commented
현재 로그인 API가 붙어서, 임시로 userId로 구현했던 부분들을 이제 토큰을 통해 처리하도록 다시 바꿔주시면 될 것 같아요 

HttpServletRequest 이용하시면 될겁니다 화이팅~

2024-09-25 17:55 UTC, kanguk01 requested changes
현재 로그인 API가 붙어서, 임시로 userId로 구현했던 부분들을 이제 토큰을 통해 처리하도록 다시 바꿔주시면 될 것 같아요

HttpServletRequest 이용하시면 될겁니다 화이팅~

2024-09-26 03:02 UTC, ez23re commented
> 현재 로그인 API가 붙어서, 임시로 userId로 구현했던 부분들을 이제 토큰을 통해 처리하도록 다시 바꿔주시면 될 것 같아요
> 
> HttpServletRequest 이용하시면 될겁니다 화이팅~

2024-09-26 03:03 UTC, ez23re commented
> 아래 사항 수정했습니다.
> 
> 1. map -> dto 생성해서 응답받도록 (그에 맞게 테스트코드도 수정)
> 2. 에러핸들링: 에러코드를 작성해서 처리했습니다.
> 3. 컨트롤러 swagger 작성
> 4. 임시로 userId로 구현 -> 토큰을 통한 처리 : 제가 oauth 패키지 아직 풀 안했는데 그냥 하면 충돌 날까봐 위의 3개 수정하고 머지되면 고쳐도 될까요?

2024-09-26 03:35 UTC, kanguk01 reviewed
음 일단 보이는 부분 코멘트 달았는데 확인 부탁드려요

2024-09-26 03:35 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/Subscription/controller/SubscriptionController.java
> +            @ApiResponse(responseCode = "401", description = "인증되지 않은 사용자입니다.")
![image](https://github.com/user-attachments/assets/4a223e1f-cd56-4fab-8fa5-1249ade7c43f)
스웨거에 쓸모없는 부분에도 이렇게 리턴값 예시가 나오고 있어요 

```java
@ApiResponse(responseCode = "200", description = "리뷰가 성공적으로 작성되었습니다.",
                    content = @Content(schema = @Schema(implementation = ReviewResponseDto.class))),
```
예시 코드인데, 이렇게 필요한 부분에만 dto 예시가 뜨도록 하면 아마 저렇게 안뜰텐데 한번 수정해보셔도 좋을 것 같네요

2024-09-26 03:35 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/Subscription/service/SubscriptionService.java
![image](https://github.com/user-attachments/assets/caa8ed4c-86ee-4aa9-840f-2add030d06ac)
userId, type이, status null로 나오고

create, update도 null로 나오는 것 같은데 문제가 있는걸까요?

API 명세서를 따르신게 보이긴 하는데 
개발하시면서 유동적으로 바꾸셔도 좋아요 (지금 명세서에 부족한 부분이 많을것이므로 개발을 하면서 알아서 판단)

한 엔드포인트 (예를 들어 지금은 /subscription) 에서는 응답 값을 다 통일해도 괜찮으니까 직접 판단하시고 필요할 것 같은 값을 잘 리턴할 수 있도록 해주세욥

2024-09-26 03:35 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
👍

2024-09-26 04:35 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
> +    NOT_FOUND("활성화된 구독을 찾을 수 없습니다.", HttpStatus.NOT_FOUND);
네이밍을 더 확실하게 해주세요!!

ex) NOT_FOUND -> SUBSCRIPSTION_NOT_FOUND

다른 에러와 겹칠 가능성이 있습니다!!

2024-09-26 06:00 UTC, kanguk01 approved these changes
<img width="318" alt="image" src="https://github.com/user-attachments/assets/b627a2b5-baa4-445b-a0be-9aa24e021674">
userId가 null로 나오는 문제는 여전하네요 이부분은 토큰통한 인증 붙이면서 해결 부탁드려요

<img width="456" alt="image" src="https://github.com/user-attachments/assets/2f01a60b-664b-4d0d-9ce3-f91bd5e9e030">
그리고 이건 크게 문제 되지는 않지만 (어차피 토큰기반으로 할거라서)
없는 userId를 입력하면 그냥 500이 터지는데 이런부분도 처리하면 더 견고해질 것 같기는 합니다! 

근데 지금 로직에서는 괜찮으니 참고만 해주세요

2024-09-26 10:46 UTC, merged