[feature]: Team CRUD 구현
kakao-tech-campus-2nd-step3/Team3_BE pull request #29
Opened 2024-09-29 14:47 UTC by kimsongmok

## 📄요약

> TEAM CRUD를 구현해보고, 팀하나에는 유저가 다수 있고, Team 엔티티에서 유저도 팀을 다수로 가질 수 있기때문에 다대다로 고쳤습니다.

## 🖋️작업 내용

- [ ] 생성
- [ ] 조회
- [ ] 수정
- [ ] 삭제

## 📷스크린샷

## ❗참고 사항
유저 정보를 가지고 올 수 있도록 Team 엔티티에 user_id를 넣었습니다.

## 🔗이슈
close #이슈번호

2024-09-30 01:42 UTC, kanguk01 requested changes
[의문점] 

팀을 생성하면 그 사람이 관리자가 될텐데, 그런 부분에 대한 처리가 정확히 있는건지 궁금하네요
Team은 ERD를 급하게 짜서 좀 논리적 빈약이 있을 수가 있는데, 혹시 구현하면서 문제를 겪으시진 않으셨나요??

그리고 만약 관리자나 팀원에 대한 로직을 추가한다면, 현재까지 구현된 다른 api들처럼 유저 인증을 받고 그 유저가 팀원인지, 관리자인지를 처리하는 부분이 필요할 것 같아요 
지금은 코드에 인증에 대한 부분이 없으니까요

2024-09-30 01:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
Swagger 설명 추가 부탁드려요~ 형식은 다른 api 참고해서 디테일하게 작성해주세요

2024-09-30 01:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +            .orElseThrow(() -> new RuntimeException("팀을 찾을 수 없습니다."));
에러 핸들링은 기존에 저희가 만들어둔 형식 이용해서 처리해주세요

2024-09-30 01:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/entity/Team.java
>    private User user;
코드가 헷갈리는데 이 user랑

2024-09-30 01:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/entity/Team.java
> +}
이 users랑 다른점이 뭔지 알 수 있을까요? 관리자와 멤버? 정확히 어떤 건지 모르겠네요

2024-09-30 02:12 UTC, kanguk01 commented
그리고 weekly/4 는 이제 끝났기 때문에 weekly/5로 머지 대상 변경해주세용

2024-09-30 09:55 UTC, kanguk01 reviewed
잡다한 부분만 확인해주세용~~

2024-09-30 09:55 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
> +  )
스웨거 설명 추가하신건 좋아요 근데 좀 더 디테일하게 작성할 수 있어요! (매개변수에 관한 설명, 입/출력 바디 예시 등)
다른 API 보면서 참고해주시면 감사하겠슴당

2024-09-30 09:55 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/entity/TeamUserRelation.java
> +}
오 중간 테이블 설정한건 좋은 방법같아보이네요

2024-09-30 09:55 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +            .orElseThrow(() -> new BusinessException(ErrorCode.USER_NOT_FOUND));
👍

2024-09-30 09:55 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +    User userToPromote = userRepository.findById(userId)
뭔가 쭉 코드가 중복되는데 이부분 더 깔끔하게 할 수는 없을까요?

2024-09-30 13:47 UTC, kimsongmok commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +    User userToPromote = userRepository.findById(userId)
코드 중복 해결해보았는데 한번 확인해주세요!

2024-09-30 13:47 UTC, kimsongmok commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
> +  )
일단 설명 추가해보았습니다!

2024-09-30 14:01 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +}
이런 식으로 메소드 분리한건 좋은거같아요 
딱 봐도 코드가 불필요하게 중복돼보인다 싶으면 항상 고려해주세용

2024-09-30 14:12 UTC, kimsongmok commented on src/main/java/com/splanet/splanet/team/service/TeamService.java
> +}
네! 알겠습니다

2024-09-30 14:49 UTC, kanguk01 approved these changes
고생하셨어요~

2024-09-30 14:49 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
> +  }
👍  만족

2024-10-06 15:42 UTC, kanguk01 requested changes
문제가 생기는 부분이 꽤 있네요 확인해주시고 수정 부탁드립니다 🥲

그리고 테스트가 힘들텐데, 최신거 풀받고 테스트유저 이용해서 테스트를 직접 해보시는게 좋을 것 같아요 


그리고 지금 테스트코드도 없는데, 이것때문에 기본적인 로직에서 오류가 나는 것을 잘 캐치하지 못한 것 같네요 
테스트코드 작성하기 어려운 부분은 없으니, 테스트코드를 통해 항상 논리적 비약을 채우면서 짜시면 좋을 것 같아요!

2024-10-06 15:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
<img width="709" alt="image" src="https://github.com/user-attachments/assets/777597b1-943a-4578-94ee-eab911dfe108">
보시면 Swagger 예시 리턴 형태랑 실제 리턴 형태랑 달라요 둘 중 하나로 맞춰주세요 

그리고 예전에도 말씀드렸는데 user 정보를 다 가져올 필요가 있을까요? Dto로 처리가 안되나요? 한번 이부분도 알아보시면 좋을 것 같네요

2024-10-06 15:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/5a184333-1cad-4ef7-9569-8d43724cf5c6">
그리고 400에도 예시값이 저렇게 있는데 이부분도 수정 부탁드려요

2024-10-06 15:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
<img width="584" alt="image" src="https://github.com/user-attachments/assets/1f7a431b-2b35-4d36-81a4-ff30825bdcbb">
이부분도 마찬가지에요 
스웨거에서는 `유저가 성공적으로 초대되었습니다.` 라고 나와야할 것 같은데 실제로는 204만 뱉죠? 이런부분이 다 통일이 필요합니다

2024-10-06 15:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
<img width="631" alt="image" src="https://github.com/user-attachments/assets/816425da-30a4-4882-ba5f-774058a6d73c">

그리고 빼먹은게 이부분같네요 

본인 초대는 본인이 조회를 할 수 있어야하고 그걸 본인이 처리할 수 있어야하는데 지금은 다른사람이 다른 유저의 초대를 수락/거절을 할 수가 있어요 

본인의 초대 목록을 확인할 수 있어야하고/ 초대는 본인만 처리할 수 있어야해요

2024-10-06 15:42 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/controller/TeamController.java
<img width="494" alt="image" src="https://github.com/user-attachments/assets/66494931-c69e-47d6-9c77-2226876fcf82">

팀원 조회에서 팀원이 추가된 후에 API를 날리니까 문제가 생기네요 

```
ERROR 70520 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor]] with root cause

com.fasterxml.jackson.databind.exc.InvalidDefinitionException .....
```

이런 에러 터지는데 확인해주세요

2024-10-09 06:50 UTC, kanguk01 reviewed
그리고 제가 5주차 피드백 반영하면서 한것처럼 컨트롤러를 인터페이스와 구현체로 나눠서 스웨거 문서화 부분을 분리하면 좋을 것 같아요!!
피알 참고해주세요

2024-10-09 06:50 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/user/dto/UserDto.java
> +}
저번주 피드백 주셨던것처럼 record 사용하는건 어떨까요?!

2024-10-10 00:01 UTC, kanguk01 reviewed
<img width="510" alt="image" src="https://github.com/user-attachments/assets/6a3f2374-6cf4-4378-8f1e-edffe1153d3f">

유저 초대 부분 40x 부분에 맞지 않는 예시 응답값이 들어가있네요~ 이부분 없애주세욥

2024-10-10 00:10 UTC, kanguk01 reviewed
```
o.s.s.w.a.AnonymousAuthenticationFilter  : Did not set SecurityContextHolder since already authenticated UsernamePasswordAuthenticationToken [Principal=3, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[]]
Hibernate: 
    select
        t1_0.id,
        t1_0.created_at,
        t1_0.deleted,
        t1_0.team_name,
        t1_0.updated_at,
        t1_0.user_id,
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        team t1_0 
    join
        user u1_0 
            on u1_0.id=t1_0.user_id 
    where
        t1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        tur1_0.id,
        tur1_0.role,
        tur1_0.team_id,
        tur1_0.user_id 
    from
        team_user_relation tur1_0 
    where
        tur1_0.team_id=? 
        and tur1_0.user_id=?
Hibernate: 
    select
        tur1_0.id,
        tur1_0.role,
        tur1_0.team_id,
        tur1_0.user_id 
    from
        team_user_relation tur1_0 
    where
        tur1_0.team_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
2024-10-10T09:06:07.149+09:00 TRACE 82634 --- [nio-8080-exec-5] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match request to [Is Secure]
```

> 팀 멤버 조회 단 **한번** 실행했을때의 로그입니다. 

조회 한번 치고 쿼리를 너무 많이 날린다고 생각드시지 않나요?
들어보셨을지는 모르겠지만, N+1 문제입니다

정말 중요한 내용이니 따로 알아보시는게 좋을 것 같고, 어떻게 해결할 수 있을지 고민해보면 좋을 것 같아요

2024-10-10 01:48 UTC, kimsongmok commented
### 1. DTO로 먼저 데이터 취합, 2. Repository 단에서 JPQL 사용 조회, 3. 서비스단에 적용

이런식으로 적용해서 기존 8번을 3번으로 줄였습니다. 혹시 더 필요하신 부분 있을까요??

2024-10-10 04:13 UTC, kanguk01 approved these changes
정말 길게 고생하셨습니다!! 머지할게요~

2024-10-10 04:13 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/team/repository/TeamUserRelationRepository.java
> +
참고로 해당 API 뿐만 아니라 연관관계가 있는 테이블의 조회를 할 때는 해당 N + 1 문제를 염두에 두셔야 합니다!! 

다른 API도 이런 부분이 분명 있으니 나중에 다 체크하면 좋을 것 같네요

2024-10-10 04:21 UTC, merged