[feature]: friend API 구현
kakao-tech-campus-2nd-step3/Team3_BE pull request #63
Opened 2024-10-11 14:39 UTC by ez23re

## 📄요약

> 친구, 친구 요청 api 구현했습니다. 테스트유저랑 요청 보내보고 거절, 수락해보고 플랜조회 했습니다. 놓친 부분 있을 것 같은데 확인해주십쇼

## 🖋️작업 내용

- [ ] 친구api
- [ ] 서비스로직 테스트코드

## 📷스크린샷
![스크린샷 2024-10-11 231517](https://github.com/user-attachments/assets/f68aa146-9585-472c-9669-4dfdfdc7ee0c)

## ❗참고 사항
아래 이슈에서 feat/51-friend-crud 브랜치 만들어둔 것을 잊고 새로 파서 연결이 안되어있습니다!

## 🔗이슈
close #51

2024-10-11 16:47 UTC, kanguk01 requested changes
전체적으로 문제가 될 상황들이 핸들링이 이뤄지지 않은 것 같아요 
이부분 신경써주시고 테스트도 그에 맞는 부분을 추가해주시면 좋을 것 같아요

테스트코드가 필요한 이유가, 이런 부분에서도 있어요 
테스트 코드를 작성하려면 엣지 케이스를 먼저 생각하는게 일반적인데, 이런 과정에서 문제가 될 상황들을 처리할 수 있거든요

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
> +        Long receiverId = request.receiverId();
요청하는 유저 Id를 저렇게 직접 입력받아야 했을까요?!
어차피 본인일텐데, 저희 늘 하던 토큰을 통해 인증받는 어노테이션을 쓰면 더 논리적으로 맞을 것 같아요~

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    }
![image](https://github.com/user-attachments/assets/84c1af5e-e9ba-47af-81cf-5a8a5c78a8fa)
요청 보냈는데 id에 null이 들어간채로 리턴되네요 리턴하는 부분이 문제가 있는 것 아닐까요?!

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    }
![image](https://github.com/user-attachments/assets/dece8d7d-4844-449c-a86d-7e7ecd7c3276)

1. 본인이 본인에게도 요청이 전송이 되네요

2. 보낸 요청 목록 조회에서는 requester 정보가 어차피 본인일텐데 requesterId만 나오는 것처럼 보이네요
지금 보면 실제로는 receiverId 가 출력되는게 맞긴 한데 네이밍이 좀 모호하게 된 것 같아요 Dto를 나누든가? 더 확실히 구별하는게 좋겠어요

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    }
![image](https://github.com/user-attachments/assets/f7c6a3c9-89ea-4424-99b7-0f96ee1f986b)

자기랑 자기가 친구가 됐네요 이런 부분은 아에 막는게 좋을 것 같아요 혹시 모를 사이드 이펙트를 위해서...

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/dto/FriendRequestResponse.java
> +}
Dto를 어디서는 record 어디서는 그냥 class 
통일성이 안맞아요 record로 쭉 밀고 가도 좋지 않을까요?

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +        friendRequestRepository.save(friendRequest);
set 하이요

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +        friendRequestRepository.save(friendRequest);
set 하이요 22

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    }
위에서 언급은 했는데, 혹시 record를 사용하지 않은 특별한 이유가 있었던 걸까요?!

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    public FriendRequestResponse acceptFriendRequest(Long requestId) {
![image](https://github.com/user-attachments/assets/e83b586d-7af5-4126-8a4b-f992939a06db)
같은 요청이 계속 받아지네요 
한번 ACCEPTED 됐다면 안받아져야 옳은 것 같아요

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    public FriendRequestResponse acceptFriendRequest(Long requestId) {
요청을 거절했다 수락했다 거절했다 수락했다.... 해도 그냥 계속 변하네요 
상태가 PENDING이 아닌 이상 이러한 상태 변화를 막아야 할 것 같아요

2024-10-11 16:47 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    }
![image](https://github.com/user-attachments/assets/a6afef5d-2fad-483f-9acc-88534f38ea87)
요청 또한 계속 보내지네요

2024-10-12 18:52 UTC, kanguk01 requested changes
`N+1` 문제같이 중요하지만 어려운 부분을 짚어드렸는데, 이 부분은 바로 수정을 억지로 하지는 않으셔도 돼요 
워낙 어려운 내용이라 (사실 저도 제대로 해결하는 방법을 몰라요) 길게 공부해도 모자랄 내용이라서 
시간 여유가 날 때 제대로 공부해보시고 최적의 방법을 공유해주시면 좋을 것 같아요

로직 부족한 부분은 보완해서 테스트코드까지 추가로 작성 부탁드려요

친구나 팀같은 관계가 들어가는 부분은 신경써야할 부분이 많기때문에 이런 부분이 나오는건 당연한거니까 너무 조급해하지 않으셔도 돼요

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +
![image](https://github.com/user-attachments/assets/6e6ad05e-fc55-4695-98fd-eb187539c6e9)
👍

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +        }
![image](https://github.com/user-attachments/assets/766ec627-7fec-4567-99d1-fd9d5e125a9d)
👍

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    public ReceivedFriendRequestResponse acceptFriendRequest(Long requestId) {
![image](https://github.com/user-attachments/assets/f216bff9-bcc8-4614-a806-8ab9f8b9ad4d)

본인이 보낸 요청을 본인이 받아버릴 수 있네요 (실제로 친구 목록에 저장까지 됨)

요청은 자기한테 온것만 처리할 수 있도록 제한을 걸어야 할 것 같아요

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friend/controller/FriendController.java
> +public class FriendController implements FriendApi {
![image](https://github.com/user-attachments/assets/c9e472b0-259e-448a-9b5e-c6c4cb0ae997)

백년가약? 
친구 맺으면 못끊네요 Delete도 만들어주세용

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friend/controller/FriendApi.java
> +}
![image](https://github.com/user-attachments/assets/d5cd9bcd-3aaa-4181-ab07-6e135a5466dd)

본인 ID는 JWT 인증 맞지만 친구 아이디는 JWT 인증이 아니니까 설명 수정해주셔야 할 것 같아요

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friend/service/FriendService.java
> +    public ResponseEntity<List<PlanResponseDto>> getFriendPlan(Long friendId, Long userId) {
![image](https://github.com/user-attachments/assets/2ee85c72-f4ec-4b99-8384-c65603bf4d7f)
 
친구로 맺어지지 않은 사용자도 플랜이 조회가 되네요 (친구 목록 싹 비우고 조회했는데 됨)
친구인 유저만 조회가 되도록 막아야하지 않을까요?!

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friend/service/FriendService.java
> +        }
개인적인 생각인데 플랜이 정말 비어있을 수도 있는데 냅다 404 뱉는거는 약간 애매하다고? 생각들어요 
그냥 빈 배열을 리턴해도 괜찮지 않을까요? 이건 애매하긴 해네요...

2024-10-12 18:52 UTC, kanguk01 commented on src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
테스트 탄탄해진건 좋아요
근데 아직은 좀 더 채워야할 부분이 있네요 같이 수정해주시면 좋을 것 같아요~! 👍

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +    public List<ReceivedFriendRequestResponse> getReceivedFriendRequests(Long userId) {
```
Hibernate: 
    select
        fr1_0.id,
        fr1_0.created_at,
        fr1_0.deleted,
        fr1_0.receiver_id,
        fr1_0.requester_id,
        fr1_0.status,
        fr1_0.updated_at 
    from
        friend_request fr1_0 
    where
        fr1_0.requester_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
```

보낸요청 조회, 받은요청 조회 모두 공통인데 

API 호출 한번했는데 쿼리가 이만큼 터져요 데이터도 없는데

만약 데이터를 더 늘려볼까요?

```
Hibernate: 
    select
        fr1_0.id,
        fr1_0.created_at,
        fr1_0.deleted,
        fr1_0.receiver_id,
        fr1_0.requester_id,
        fr1_0.status,
        fr1_0.updated_at 
    from
        friend_request fr1_0 
    where
        fr1_0.requester_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
```

엄청나죠? 

`N + 1` 문제인데, 계속 제가 말할만큼 매우 중요한 부분입니다

이부분은 따로 공부하셔서 최적의 방법으로 해결하시면 좋을 것 같아요

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
> +        friendRequestRepository.save(friendRequest);
set은 아직 그대로네요!

2024-10-12 18:52 UTC, kanguk01 commented on src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java
> +    private User receiver;
현재 `(fetch = FetchType.EAGER)`  상태인데,(기본값) 이때문에 나올 수 있는 문제가

만약 친구 요청 API를 한번 날리면 

```
Hibernate: 
    select
        f1_0.id 
    from
        friend f1_0 
    where
        f1_0.user_id=? 
        and f1_0.friend_id=? 
    limit
        ?
Hibernate: 
    select
        fr1_0.id,
        fr1_0.created_at,
        fr1_0.deleted,
        fr1_0.receiver_id,
        fr1_0.requester_id,
        fr1_0.status,
        fr1_0.updated_at 
    from
        friend_request fr1_0 
    where
        fr1_0.receiver_id=? 
        and fr1_0.requester_id=? 
        and fr1_0.status=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    select
        u1_0.id,
        u1_0.created_at,
        u1_0.deleted,
        u1_0.is_premium,
        u1_0.kakao_id,
        u1_0.nickname,
        u1_0.profile_image,
        u1_0.updated_at 
    from
        user u1_0 
    where
        u1_0.id=?
Hibernate: 
    select
        s1_0.id,
        s1_0.created_at,
        s1_0.deleted,
        s1_0.end_date,
        s1_0.start_date,
        s1_0.status,
        s1_0.type,
        s1_0.updated_at,
        s1_0.user_id 
    from
        subscription s1_0 
    where
        s1_0.user_id=?
Hibernate: 
    insert 
    into
        friend_request
        (created_at, deleted, receiver_id, requester_id, status, updated_at) 
    values
        (?, ?, ?, ?, ?, ?)
```

이번엔 `GET` 도 아닌데 N+1 마냥 쿼리가 여러번 터져요
이건 또 즉시로딩이여서 관련 엔티티를 한번에 다 불러오기 때문에 그런건데, 이 부분도 고민해보면 좋을 것 같아요

2024-10-13 16:26 UTC, ez23re commented
`N + 1` 은 찾아보고 수정할 수 있도록 하겠습니다. 리뷰 반영한 부분 확인해주세요 매번 감사합니다!

2024-10-14 06:00 UTC, kimsongmok requested changes
N+1 문제 제가 해결한 경험이 있어서 말씀드리자면, fetch join을 사용하는 것이 일반적입니다!
또, EntityGraph가 있는데요, 이를 적용하다보면 확실히 쿼리가 적어지는 것이 보일겁니다..!

2024-10-14 17:23 UTC, kanguk01 approved these changes
깔끔하네요 고생하셨습니다

2024-10-15 08:50 UTC, kimsongmok approved these changes

2024-10-25 04:20 UTC, merged